server:
  port: 9010

spring:
  application:
    name: system-eureka-server1

eureka:
  instance:
    hostname: eureka1
  client:
    ##这里要覆盖application的设置，不然会读取application文件导致unavailable-replicas
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://eureka2:9011/eureka/