server:
  port: 9011

spring:
  application:
    name: system-eureka-server2

eureka:
  instance:
    hostname: eureka2
  client:
    ##这里要覆盖application的设置，不然会读取application文件导致unavailable-replicas
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://eureka1:9010/eureka/